---
global:
  hostname: 'vyos-s1.engyak.net'
  domain: 'engyak.net'
  timezone: 'US/Alaska'
interfaces:
  eth1:
    ipv4: '10.6.194.0/31'
    ipv6: '2610:100:6000:de2::1/64'
  eth2:
    ipv4: '10.6.194.2/31'
    ipv6: '2610:100:6000:de3::1/64'
  l0:
    ipv4: '10.6.198.1/32'
    ipv6: '2610:100:6000:def::1/128'
bgp:
  asn: '64909'
  rid: '10.6.198.1'
  leaf1: '10.6.194.1'
  leaf1asn: '64916'
  leaf2: '10.6.194.3'
  leaf2asn: '64917'
  keepalive: '4'
  holdtime: '12'
