---
- hosts: vyos_vclos_leafs
  tasks:
    - name: Gather Facts on Leafs!
      vyos.vyos.vyos_facts:
    - name: Print Facts on Leafs!
      ansible.builtin.debug:
        var: ansible_net_gather_subset.neighbors
- hosts: vyos_vclos_spines
  tasks:
    - name: Gather Facts on Spines!
      vyos.vyos.vyos_facts:
