---
- hosts: vyos_vclos_leafs
  tasks:
    - name: Gather Facts on Leafs!
      vyos.vyos.vyos_facts:
        gather_subset: all
    - name: Print Facts on Leafs!
      ansible.builtin.debug:
        var: hostvars[ansible_net_gather_subset]
- hosts: vyos_vclos_spines
  tasks:
    - name: Gather Facts on Spines!
      vyos.vyos.vyos_facts:
